### ISSUE TITLE
What about community.grafana collection ?

### ISSUE THREAD

**Issue by rrey** [grafana/grafana-ansible-collection#11]
Hello, https://github.com/ansible-collections/community.grafana maintainer here 👋 

Could you share your plans around this newly created collection versus the existing one in the Ansible community namespace ?
I would gladly discuss possibilities to avoid concurrent collections for Grafana.

Don't hesitate to contact me.

**Comment by ishanjainn** [comment]
Hi,
Great question, This collection is only supported for Grafana Cloud and would not work for OSS deployments of Grafana currently. As per my understanding, The community.grafana is better used for OSS deployments of Grafana.

**Comment by rrey** [comment]
Okay thanks for the feedback !
