### ISSUE TITLE
Grafana Datasource - wrong parameter name for community.grafana.grafana_datasource

### ISSUE THREAD

**Issue by kamszp** [grafana/grafana-ansible-collection#122]
In `roles/grafana/tasks/datasources.yml` there is `grafana_datasource` module calling from `community.grafana` collection in which there is wrong name of parameter:
`url` instead of `ds_url`

[Here](https://docs.ansible.com/ansible/latest/collections/community/grafana/grafana_datasource_module.html#parameter-ds_url) is link to `comunity.grafana.grafana_datasource` documentation - there is no alias for `ds_url`.

It cause errors like this:
```
TASK [grafana.grafana.grafana : Ensure datasources exist (via API)] ************
Wednesday 18 October 2023  09:42:06 -0500 (0:00:00.048)       0:01:36.556 *****
failed: [server01] (item={'name': 'prometheus', 'type': 'prometheus', 'access': 'proxy', 'url': 'https://server01:9090', 'basicAuth': True, 'basicAuthUser': 'prom_user', 'basicAuthPassword': 'prom_pass'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "access": "proxy",
        "basicAuth": true,
        "basicAuthPassword": "prom_pass",
        "basicAuthUser": "prom_user",
        "name": "prometheus",
        "type": "prometheus",
        "url": https://server01:9090
    }
}

MSG:

state is present but all of the following are missing: ds_url
```

**Comment by dergudzon** [comment]
Probably this can help: https://github.com/grafana/grafana-ansible-collection/pull/162
