### ISSUE TITLE
grafana_url unsupported in grafana.grafana.datasource module

### ISSUE THREAD

**Issue by mac133k** [grafana/grafana-ansible-collection#144]
I was trying to provision Prometheus datasource in my on-prem Grafana server using Grafana Ansible collection module. I created a task based on the example in https://docs.ansible.com/ansible/latest/collections/grafana/grafana/datasource_module.html#ansible-collections-grafana-grafana-datasource-module. My play failed with the following error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (grafana.grafana.datasource) module: grafana_url Supported parameters include: dataSource, grafana_api_key, stack_slug, state"}
````
When I commented out the line with grafana_url in the task list the error I got was:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: stack_slug"}
```

I have a set of datasources for Prometheus, Alertmanager and Loki that I need to provision via API, but community.grafana does not support Alertmanager DS, so I switched to grafana.grafana and found this problem. I use grafana.grafana collection v2.2.4, I have not tried any other version.

**Comment by ishanjainn** [comment]
This is wierd, We did have `stack_slug` instead of `grafana_url` a while back `1.x.x` I think, Can you once double check that the collection version is `2.2.4` because I don't find any mention of stack_slug in the datasource source code

**Comment by mac133k** [comment]
Yes, that seemed weird to me too. I just realised I had some older version of grafana.grafana already installed and it was not updated for some reason after I set the version number to 2.2.4 in ansible_requirements.yml. After removing the collections from disk and installing the actualy v2.2.4 the datasource module started to work as expected. Apologies for the confusion. I'm closing this issue.
