### ISSUE TITLE
Add support for feature_toggles in grafana.ini

### ISSUE THREAD

**Issue by mmaakdotsource** [grafana/grafana-ansible-collection#163]
Hi,

if i understand correctly there is no option at the moment to setup feature_toggles in grafana.
Is there an option to set [feature_toggles] in grafana.ini config file?

I want to set:

[feature_toggles]
autoMigrateOldPanels = true

Thanks for advice

**Comment by LexVar** [comment]
Hi, I submitted a PR to support feature_toggles #173
