### ISSUE TITLE
The run_once from #136 breaks multi-arch runs

### ISSUE THREAD

**Issue by wzzrd** [grafana/grafana-ansible-collection#171]
The `run_once` directive added in #136 breaks jobs that run over multiple architectures. Because of the run_once, the role now only downloads the grafana_agent zip file once, it seems, although it needs to download it multiple times if there are multiple CPI architectures involved:

```
TASK [grafana.grafana.grafana_agent : Extract grafana-agent.zip] ***************
>f++++++.?? grafana-agent-linux-amd64
changed: [intelhost -> localhost]
TASK [grafana.grafana.grafana_agent : Set local path] **************************
ok: [intelhost]
ok: [armhost]

TASK [grafana.grafana.grafana_agent : Propagate downloaded binary] *************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [armhost]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/grafana-agent/grafana-agent-linux-arm64' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
ok: [intelhost]
```

I get what the run_once is trying to do (downloading the agent only once and copy the same binary to all targeted hosts), but that does not work if the binary is supposed to be different across various hosts. I suggest remove the `run_once` introduced by #136 for now: release 2.2.4 worked fine without that PR, release 2.2.5 with that PR fails completely.

**Comment by gardar** [comment]
Duplicate: #166
