### ISSUE TITLE
Failed to upgrade Grafana from 10.3 to 11.0.0 

### ISSUE THREAD

**Issue by zhan9san** [grafana/grafana-ansible-collection#220]
Error message:

```log
logger=settings t=2024-06-12T00:01:23.550962896-07:00 level=info msg="Starting Grafana" version=11.0.0 commit=277ef258d4b9a5acdf2932347c6a4ca72d739b28 branch=HEAD compiled=2024-06-12T00:01:23-07:00
logger=settings t=2024-06-12T00:01:23.551446178-07:00 level=error msg="Option '[alerting].enabled' cannot be true. Legacy Alerting is removed. It is no longer deployed, enhanced, or supported. Delete '[alerting].enabled' and use '[unified_alerting].enabled' to enable Grafana Alerting. For more information, refer to t
he documentation on upgrading to Grafana Alerting (https://grafana.com/docs/grafana/v10.4/alerting/set-up/migrating-alerts)"
```

No customized alerting configured.

It can be fixed by adding `grafana_alerting: {}` in my own playbook variable.

It would be great if it can be fixed in the Grafana role.

**Comment by voidquark** [comment]
https://github.com/grafana/grafana-ansible-collection/pull/215

**Comment by HamzaKhait** [comment]
Hello @zhan9san 
Is your workaround still working ? 
I've set `grafana_alerting: {}` in my playbook vars but I still have the same error

**Comment by voidquark** [comment]
I guess we can close this once the new collection release is created. This version issue was resolved by https://github.com/grafana/grafana-ansible-collection/pull/215 .
