### ISSUE TITLE
Configure exception for debsums regarding promtail.service in the promtail role?

### ISSUE THREAD

**Issue by funkyfuture** [grafana/grafana-ansible-collection#227]
as the `promtail` role alters the `/etc/systemd/system/promtail.service` that is previously installed from `.deb` package (on systems where these are used for deployment) i get reports by [debsums](https://packages.debian.org/buster/debsums) about that change. i can configure the exception regarding that file for debsums within my general systems configuration, but could also provide a patch to include that in the role here. please let me know whether that is of interest for you.

**Comment by voidquark** [comment]
I think it would be better if you manage this yourself. You can use post tasks to perform the customization needed in your environment.

**Comment by funkyfuture** [comment]
okay, i'm assuming you're not referring to some kind of hook that the role would provide with "post tasks" as i can't find something like it.

**Comment by voidquark** [comment]
> okay, i'm assuming you're not referring to some kind of hook that the role would provide with "post tasks" as i can't find something like it.

No, what I mean is this https://www.redhat.com/sysadmin/ansible-pretasks-posttasks
