### ISSUE TITLE
Important information for collection maintainers that is going to be included in the Ansible package

### ISSUE THREAD

**Issue by Andersson007** [grafana/grafana-ansible-collection#26]
Dear maintainers,
as the collection will get included very soon, could you all please:

- Subscribe to the [news-for-maintainers](https://github.com/ansible-collections/[news-for-maintainers](https://github.com/ansible-collections/news-for-maintainers)) repo and track announcements there. The ansible-core folks publish there changes related to CI  (and not only) and actions need to bee done in order to keep the runs green. Otherwise, your CI will get red one day in PRs for unclear reasons.
- Optionally but highly recommended, subscribe to [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn). Feel free to leverage it when you need community's feedback or for important announcements like new releases of this collection.
- We have the [Maintainer guidelines](https://github.com/ansible/community-docs/blob/main/maintaining.rst). Might be useful to take a look.
- Share the above with future maintainers.
- I would suggest putting the above info in README or reflect this another way, up to you.

Thanks!

**Comment by ishanjainn** [comment]
Thanks @Andersson007 , Ill add this to README post holidays.

[NOT URGENT] Also a quick question, Are the included collections automatically included in the [collections index](https://docs.ansible.com/ansible/latest/collections/index.html) page. Thinking would need to remove the self hosted documentation and update links at a few places if thats the case.
