### ISSUE TITLE
Alloy Role Improvements

### ISSUE THREAD

**Issue by voidquark** [grafana/grafana-ansible-collection#280]
This issue was created to track all changes made in this PR.

## Reason for Implementing These Changes 🎯

This role has been aligned with the Promtail, Loki, and Mimir Ansible roles to follow a consistent logic for `deb`/`rpm` deployment. The role now supports RedHat, RockyLinux, AlmaLinux, Debian, and Ubuntu out of the box. I've also introduced new features and reduced configuration complexity by minimizing the number of required variables.

## Deprecated Variables ⚠️

- `alloy_arch_mapping` - Removed. Arch is auto-detected.
- `alloy_arch` - Removed. Arch is auto-detected.
- `alloy_binary_url` - Removed and replaced with `alloy_download_url_rpm` and `alloy_download_url_deb`.
- `alloy_service_name` - Removed. The Systemd file is included with the `deb`/`rpm` package.
- `alloy_working_dir` - Removed. The directory is automatically created during the `deb`/`rpm` installation.
- `alloy_installation_dir` - Removed. It's created automatically during the `deb`/`rpm` package installation.
- `alloy_environment_file` - Removed. The environment file is created automatically during the `deb`/`rpm` package installation. Debian/Ubuntu systems use `/etc/default/alloy`, while RHEL-based systems use `/etc/sysconfig/alloy`.
- `alloy_config_dir` - Removed. The config now uses the standard `/etc/alloy` directory, which is created during the `deb`/`rpm` package installation.
- `alloy_config_file` - Removed. The configuration is templated into `/etc/alloy/config.alloy` following the Grafana Alloy documentation.
- `alloy_service_user` - Removed. By default, the alloy user is created during the installation of the `deb`/`rpm` package, in alignment with Grafana Alloy documentation. You can use `alloy_systemd_override` if you wish to run it as a different user (e.g., root). See `defaults/main.yml` for details on this use case.
- `alloy_service_group` - Removed. By default, the alloy group is created during the installation of the `deb`/`rpm` package.
- `alloy_flags_extra` - Removed. All extra flags can now be configured via environment variables. See `alloy_env_file_vars` with the example of `CUSTOM_ARGS` in `defaults/main.yml`.
- `alloy_start_after_service` - Removed. If the configuration is correct, Alloy starts automatically, and the role will not fail. The role is idempotent.

## Breaking Changes 🚨

Installation is now handled via `rpm` and `deb` packages, which create all necessary files:
  - Config in /etc/alloy
  - Systemd unit file shipped directly with the package at `/usr/lib/systemd/system/alloy.service`. The role follows standard Systemd structure with a drop-in file. See the example in `defaults/main.yml` and search for the `alloy_systemd_override` variable.
  - The environment file is automatically created and can be extended with additional environment variables.
  - `/var/lib/alloy` - is automatically created during installation to store alloy data.
  - The role will fail if `alloy_config` is empty, as it templates the entire content of this variable. See the example in `defaults/main.yml`. Alloy does not currently support config validation, so syntax issues cannot be verified.

## New Features ✨

- `alloy_version` – Now defaults to `latest`, which scrapes the GitHub API for the latest released version. You can also pin a specific version, such as `1.4.2`, if needed.
- `alloy_uninstall` - By default, this is set to `false`, so no uninstallation is performed. Setting it to `true` will uninstall and clean up the entire Alloy installation.
- `alloy_expose_port` - By default, this is set to `false`. If set to `true`, it ensures that the Firewalld port is exposed. By default, it uses TCP port `12345`. To change this, configure the environment variable `CUSTOM_ARGS: "--server.http.listen-addr=0.0.0.0:54321"` to listen on port `54321` and all interfaces, or pin a specific IP. For more complex configurations, it's recommended to extend with your own playbook.

## Migration Guide 🔄

The cleanest way to migrate is to create a playbook or manually clean up your current installation, populate the necessary variables, and redeploy with the new role. Follow these steps:

1. Stop the Alloy systemd unit before starting.
2. Remove the following directories: `/var/lib/alloy`, `/opt/alloy`, `/etc/alloy`
3. Remove the binary: `/usr/local/bin/alloy-linux-{{ arch }}` (e. g. `/usr/local/bin/alloy-linux-amd64` or `/usr/local/bin/alloy-linux-arm64`
4. Remove the file: `/etc/systemd/system/alloy.service`
5. Remove the `alloy` user and group.
6. Deploy Alloy with the new role. 🚀

**Comment by PabloEForgeFlow** [comment]
While I'm all in for using standard system packaging, this looks like an overhaul big enough that a migration task or similar should be provided to ease the process. I'm not sure if there's a standard procedure in ansible for these type of scenarios, but at the very least it would be nice to provide users with a heads-up and a playbook implementing the steps you describe in the migration guide.

At a first glance the changes proposed in the PR make sense to me, but I will take a better look when I have some time.

**Comment by voidquark** [comment]
If you want a playbook to clean up the current deployment role before applying the new role, here’s a simple playbook that performs exactly what is outlined in the migration guide.

```yaml
---
- name: Cleanup alloy service
  hosts: alloy
  become: true
  tasks:
    - name: Stop Alloy service
      ansible.builtin.systemd:
        name: alloy
        state: stopped
      ignore_errors: true

    - name: Remove Alloy directories
      ansible.builtin.file:
        path: "{{ remove_me }}"
        state: absent
      loop:
        - "/opt/alloy"
        - "/etc/alloy"
        - "/etc/systemd/system/alloy.service"
      loop_control:
        loop_var: remove_me

    - name: Remove the Alloy system user
      ansible.builtin.user:
        name: "alloy"
        force: true
        state: absent

    - name: Remove Alloy system group
      ansible.builtin.group:
        name: "alloy"
        state: absent
```

**Comment by sepulworld** [comment]
group creation is broken in main branch fyi.

```
    "msg": "Group ['alloy', 'adm', 'docker'] does not exist"
```

https://github.com/grafana/grafana-ansible-collection/blob/main/roles/alloy/tasks/install.yml#L16 -  this needs to be `groups:` 

trying to pass in a list to `group:` fails

**Comment by sepulworld** [comment]
https://github.com/grafana/grafana-ansible-collection/pull/282

**Comment by voidquark** [comment]
Could you please switch back to the main branch, as the PR for improvements has been merged, and there are breaking changes. Install play was replaced with deploy play. I recommend following the migration steps and redeploying with the new role.

**Comment by sepulworld** [comment]
yeah, the migration steps are fine. There were breaking changes in the 'main' branch. Let's work together and add some relevant testing to prevent changes like that from merging into the 'main' branch.

**Comment by voidquark** [comment]
> yeah, the migration steps are fine. There were breaking changes in the 'main' branch. Let's work together and add some relevant testing to prevent changes like that from merging into the 'main' branch.

Is there anything unclear to you? The old role and the new role use different deployment methods. The new one uses deb/rpm packages, so I believe migration is necessary for a clean deployment. Is there anything specific I can assist you with?

**Comment by sepulworld** [comment]
Thanks Voidquark!

There might be another item missing on the migration steps. The binary was still left over and in the path. I'm running on an Ubuntu system. I'll see what the additional task is missing and can update here if you want

**Comment by voidquark** [comment]
> Thanks Voidquark!
> 
> There might be an item missing on the migration steps. The binary was still left over and in the path. I'm running on an Ubuntu system. I'll see what the additional task is missing and can update here if you want

I assumed the default deployment. I hope I didn’t miss anything, but if you think I did, please share the details and I will update the issue (migration steps and playbook).

**Comment by voidquark** [comment]
@sepulworld 

I've updated the migration guide and cleanup playbook. It now removes missing binary and directories.

**Comment by sepulworld** [comment]
Great! Once I remove the old binary things seem to work well coupled with the other migration steps! Thanks again. This is a great playbook !

**Comment by carlos-lehmann** [comment]
Hey @voidquark 

Do you have a release frequency or when can we expect this version to be rolled out? Also forgive the newbie question:

```
collections:
  - name: grafana.grafana
    source: https://github.com/grafana/ansible-grafana-collection.git
    version: main
  - name: community.general
````

Could I use this in my `requirements.yml` already to roll along with main or how could I test this? 

Thank you,
Carlos

**Comment by voidquark** [comment]
> Hey [@voidquark](https://github.com/voidquark)
> 
> Do you have a release frequency or when can we expect this version to be rolled out? Also forgive the newbie question:
> 
> ```
> collections:
>   - name: grafana.grafana
>     source: https://github.com/grafana/ansible-grafana-collection.git
>     version: main
>   - name: community.general
> ```
> 
> Could I use this in my `requirements.yml` already to roll along with main or how could I test this?
> 
> Thank you, Carlos

I’ll close this. It’s already implemented and available in the main branch as well as in the latest release.
