### ISSUE TITLE
The github pages documentation link 404s

### ISSUE THREAD

**Issue by mut3** [grafana/grafana-ansible-collection#37]
https://grafana.github.io/grafana-ansible-collection/ currently returns the generic github pages 404. I would really like to switch to using this module over the 2 years out of maintenance cloudalchemy one, but without docs, that's hard to do :slightly_smiling_face:

**Comment by ishanjainn** [comment]
Thanks @mut3 for bringing this up. Since this package is part of the Ansible Package now, The documentation has been moved to https://docs.ansible.com/ansible/latest/collections/grafana/grafana/

I get you found the 404 link from the README. I have updated the README with this new link now.
