### ISSUE TITLE
Grafana server role?

### ISSUE THREAD

**Issue by gardar** [grafana/grafana-ansible-collection#45]
Is there any interest in adding a role for Grafana to this collection? Or is this collection only intended for Grafana Cloud?

I'm a maintainer of the [prometheus ansible collection](https://github.com/prometheus-community/ansible) which hosts ansible roles that were previously a part of [cloudalchemy](https://github.com/cloudalchemy), cloudalchemy also has a role for grafana and I'm wondering if this could be the new home for it. ( https://github.com/cloudalchemy/ansible-grafana )

I can prepare a PR if you are interested.

**Comment by ishanjainn** [comment]
Hey @gardar 
The collection started just for Grafana Cloud because of the plugins(modules) but the Grafana Agent role works for both so that would not be a problem. Definitely interested in adding the Grafana Role and any other roles you feel would be good additions here. Thanks!
