### ISSUE TITLE
The collections doesn't support Flow mode even though the changelog says it should

### ISSUE THREAD

**Issue by VLZZZ** [grafana/grafana-ansible-collection#51]
Hi!

With the `2.0.0` release Major change `Support for Grafana Agent Flow` was introduced.
However, this seems only to set the environment variable `AGENT_MODE=flow` and the passes all unsupported arguments like `--config.file`, `--config.expand-env`, etc. which makes `grafana-agent.service` fail.
hardcoded `--config.file` argument in template - https://github.com/grafana/grafana-ansible-collection/blob/main/roles/grafana_agent/templates/grafana-agent.service.j2

![image](https://user-images.githubusercontent.com/9082481/234822144-f4b79782-4b51-434f-8d48-185b6025a03c.png)

Journalctl logs example:
```
-- Unit grafana-agent.service has finished starting up.
--
-- The start-up result is done.
Apr 26 23:06:05 <my_hostname> grafana-agent[28467]: Error: unknown flag: --config.expand-env
Apr 26 23:06:05 <my_hostname> systemd[1]: grafana-agent.service: Main process exited, code=exited, status=1/FAILURE
Apr 26 23:06:05 <my_hostname> systemd[1]: grafana-agent.service: Unit entered failed state.
Apr 26 23:06:05 <my_hostname> systemd[1]: grafana-agent.service: Failed with result 'exit-code'.
Apr 26 23:06:05 <my_hostname> systemd[1]: grafana-agent.service: Service hold-off time over, scheduling restart.
Apr 26 23:06:05 <my_hostname> systemd[1]: Stopped Grafana Agent.
-- Subject: Unit grafana-agent.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit grafana-agent.service has finished shutting down.
```

May you please elaborate on how could I take the advantage of newly introduced `Support for Grafana Agent Flow` using this collection?

**Comment by VLZZZ** [comment]
Just to give more context, I was able to run agent in the `flow` mode with a simle workaround by replacing the systemd unit definition like that:

```
    - name: Replace ExecStart for grafana-agent
      lineinfile:
        path: /lib/systemd/system/grafana-agent.service
        regexp: '^(ExecStart=[\w\/-]+)'
        line: "\\1 run {{ agent_config_file_path }}"
        backrefs: yes
    
    - name: Remove --config.file line in grafana-agent.service file
      lineinfile:
        path: /lib/systemd/system/grafana-agent.service
        regexp: '.*--config\.file.*'
        state: absent
```

And then reloading the daemon and restarting the failed `grafana-agent` service.
But all of this might be considered as a temporary workaround only and only if no additional variables which might affect the system unit configuration template conditions were set .

**Comment by ishanjainn** [comment]
Thanks for sharing @VLZZZ , @bentonam is working on a fix but ill try to highlight this in the Docs till the fix is ready
