### ISSUE TITLE
Role execution continues if curl isn't installed

### ISSUE THREAD

**Issue by Jake151** [grafana/grafana-ansible-collection#53]
At this line, curl is required to collect the current latest version from the GitHub repository. However, if curl is not present on the machine this will fail silently and continue until the role attempts to download the agent from GitHub. At this point, it does not have the version number and will fail, but it's not immediately clear that it was the lack of curl that caused the failure as there is quite a lot of logging between the actual failure and failure of the role.

https://github.com/grafana/grafana-ansible-collection/blob/86a49cc857b85d351391e7c030a9e7da26fd4db2/roles/grafana_agent/tasks/preflight/download.yaml#L7

**Comment by ishanjainn** [comment]
Ah, Able to replicate this, Ill add this as a check(If you already have something ready though, Feel free to share it).
Thanks!
