### ISSUE TITLE
Deleting folders is not idempotent

### ISSUE THREAD

**Issue by theSuess** [grafana/grafana-ansible-collection#67]
When setting a folder state to `absent`, running the playbook twice results in an error as the `404` status code is interpreted as an error

**Comment by ishanjainn** [comment]
This was a bit intentional in the sense that, Users are trying to delete a resource that doesn't exist

**Comment by theSuess** [comment]
Hm, I'd still consider having this behavior consistent with the rest of the Ansible ecosystem, as Ansible should describe the desired state (see for example the same topic in the `file` module where marking a non-existent file as absent does not fail).

If you're deploying Ansible with AWX or another centralized component, you cannot be sure that only one run will be performed.
