### ISSUE TITLE
if agent version is not defined in agent role - it fails to download

### ISSUE THREAD

**Issue by nycterent** [grafana/grafana-ansible-collection#75]
null_resource.ansible-plays (local-exec): ok: [] => {
null_resource.ansible-plays (local-exec):     "_grafana_agent_download_url": "https://github.com/grafana/agent/releases/download/v/grafana-agent-linux-amd64.zip"
null_resource.ansible-plays (local-exec): }

null_resource.ansible-plays (local-exec): fatal: [-> localhost]: FAILED! => {"attempts": 5, "changed": false, "dest": "/tmp/grafana-agent/grafana-agent.zip", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://github.com/grafana/agent/releases/download/v/grafana-agent-linux-amd64.zip"}

please disregard terraform output, it just launches ansible playbook

also i believe that defining version as latest - it constructs wrong url as well

**Comment by ishanjainn** [comment]
Thanks for raising this

**Comment by ishanjainn** [comment]
Hey, So had a discussion on this and believe that strict version needs to be mainatined to avoid breaking the unintentional breaking of the agent config. If you prefer, We can make this clear in the Docs/README

**Comment by nycterent** [comment]
i kinda understand and fine with defining version, but there are a couple of tutorials in the wild saying it will download latest version if not defined, i.e - https://grafana.com/docs/grafana-cloud/developer-resources/infrastructure-as-code/ansible/ansible-grafana-agent-linux/

**Comment by ishanjainn** [comment]
Ahh, Got it and thanks for sharing the issue, Ill get that fixed!
